[project]
name = "nlp-capstone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gensim>=4.4.0",
    "matplotlib>=3.10.8",
    "nltk>=3.9.2",
    "wordcloud>=1.9.4",
]
